// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"database/sql"
)

const consumeAuthCode = `-- name: ConsumeAuthCode :one
UPDATE auth_codes
SET consumed_at = ?
WHERE code_hash = ? AND consumed_at IS NULL AND expires_at >= ?
AND app_id = ? AND target_host = ? AND browser_hash = ?
RETURNING code_hash, subject, app_id, target_host, return_path, browser_hash, expires_at, consumed_at
`

type ConsumeAuthCodeParams struct {
	ConsumedAt  sql.NullInt64 `json:"consumed_at"`
	CodeHash    []byte        `json:"code_hash"`
	ExpiresAt   int64         `json:"expires_at"`
	AppID       string        `json:"app_id"`
	TargetHost  string        `json:"target_host"`
	BrowserHash string        `json:"browser_hash"`
}

func (q *Queries) ConsumeAuthCode(ctx context.Context, arg ConsumeAuthCodeParams) (AuthCode, error) {
	row := q.db.QueryRowContext(ctx, consumeAuthCode,
		arg.ConsumedAt,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AppID,
		arg.TargetHost,
		arg.BrowserHash,
	)
	var i AuthCode
	err := row.Scan(
		&i.CodeHash,
		&i.Subject,
		&i.AppID,
		&i.TargetHost,
		&i.ReturnPath,
		&i.BrowserHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const consumeOAuthState = `-- name: ConsumeOAuthState :one
DELETE FROM oauth_states
WHERE state_hash = ? AND expires_at >= ?
RETURNING state_hash, app_id, return_path, browser_hash, expires_at, created_at
`

type ConsumeOAuthStateParams struct {
	StateHash []byte `json:"state_hash"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) ConsumeOAuthState(ctx context.Context, arg ConsumeOAuthStateParams) (OauthState, error) {
	row := q.db.QueryRowContext(ctx, consumeOAuthState, arg.StateHash, arg.ExpiresAt)
	var i OauthState
	err := row.Scan(
		&i.StateHash,
		&i.AppID,
		&i.ReturnPath,
		&i.BrowserHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthCode = `-- name: CreateAuthCode :exec
INSERT INTO auth_codes (
    code_hash, subject, app_id, target_host, return_path, browser_hash, expires_at, consumed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, NULL)
`

type CreateAuthCodeParams struct {
	CodeHash    []byte `json:"code_hash"`
	Subject     string `json:"subject"`
	AppID       string `json:"app_id"`
	TargetHost  string `json:"target_host"`
	ReturnPath  string `json:"return_path"`
	BrowserHash string `json:"browser_hash"`
	ExpiresAt   int64  `json:"expires_at"`
}

func (q *Queries) CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) error {
	_, err := q.db.ExecContext(ctx, createAuthCode,
		arg.CodeHash,
		arg.Subject,
		arg.AppID,
		arg.TargetHost,
		arg.ReturnPath,
		arg.BrowserHash,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state_hash, app_id, return_path, browser_hash, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOAuthStateParams struct {
	StateHash   []byte `json:"state_hash"`
	AppID       string `json:"app_id"`
	ReturnPath  string `json:"return_path"`
	BrowserHash string `json:"browser_hash"`
	ExpiresAt   int64  `json:"expires_at"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthState,
		arg.StateHash,
		arg.AppID,
		arg.ReturnPath,
		arg.BrowserHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpired = `-- name: DeleteExpired :execrows
DELETE FROM oauth_states WHERE expires_at < ?
`

func (q *Queries) DeleteExpired(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpired, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :execrows
DELETE FROM auth_codes WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredCodes, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
