// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuthCode struct {
	CodeHash    []byte        `json:"code_hash"`
	Subject     string        `json:"subject"`
	AppID       string        `json:"app_id"`
	TargetHost  string        `json:"target_host"`
	ReturnPath  string        `json:"return_path"`
	BrowserHash string        `json:"browser_hash"`
	ExpiresAt   int64         `json:"expires_at"`
	ConsumedAt  sql.NullInt64 `json:"consumed_at"`
}

type OauthState struct {
	StateHash   []byte `json:"state_hash"`
	AppID       string `json:"app_id"`
	ReturnPath  string `json:"return_path"`
	BrowserHash string `json:"browser_hash"`
	ExpiresAt   int64  `json:"expires_at"`
	CreatedAt   int64  `json:"created_at"`
}
